project:
  render: 
  - "*.qmd"
  - "!sketches/"
  type: website
  output-dir: output_docs
format: 
  html:
    embed-resources: true
    smooth-scroll: true
    code-fold: true 
    toc: true
    toc-location: left
    toc-title: Table of Contents
    toc-depth: 1
    page-layout: article
    code-tools:
      source: "https://github.com/MClausonAus/datarock_data_challenge.git"
    
execute:
  warning: false
  enabled: true
  cache: true



